# Capstone Two: Preprocessing and Training Data Development

#### Clickstream Data for Online Shopping
#### Dataset: https://archive.ics.uci.edu/dataset/553/clickstream+data+for+online+shopping

In this notebook, we will be completing the three key steps of data preprocessing and training data development prior to building our machine learning model.

1. Create dummy or indicator features for categorical variables
2. Standardize the magnitude of numeric features
3. Split into testing and training datasets

In [33]:
# Import packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [35]:
# Import data and convert date from object type
df = pd.read_csv('dataset/shopping_data_cleaned.csv')
df['date'] = pd.to_datetime(df['date'])
# Convert columns to object
cols_to_object = ['country', 
                        'page 1 (main category)', 
                        'page 2 (clothing model)', 
                        'colour', 
                        'location', 
                        'model photography']
df[cols_to_object] = df[cols_to_object].astype('object')
print(df.dtypes)

year                                int64
month                               int64
day                                 int64
order                               int64
country                            object
session ID                          int64
page 1 (main category)             object
page 2 (clothing model)            object
colour                             object
location                           object
model photography                  object
price                             float64
price 2                             int64
page                                int64
date                       datetime64[ns]
dtype: object

In [37]:
# Convert price 2 to boolean
df['price 2_bool'] = (df['price 2'] == 1)

In [39]:
# Drop extra columns
df = df.drop(columns = ['year', 'month', 'day', 'price 2'])

In [41]:
# Inspect data frame
df.head()

,order,country,session ID,page 1 (main category),page 2 (clothing model),colour,location,model photography,price,page,date,price 2_bool
0,1,29,1,1,A13,1,5,1,28.0,1,2008-04-01,False
1,2,29,1,1,A16,1,6,1,33.0,1,2008-04-01,False
2,3,29,1,2,B4,10,2,1,52.0,1,2008-04-01,True
3,4,29,1,2,B17,6,6,2,38.0,1,2008-04-01,False
4,5,29,1,2,B8,4,3,2,52.0,1,2008-04-01,True

## 1. Create dummy or indicator features from categorical variables

In [44]:
# Select object type columns
dfo = df.select_dtypes(include=['object'])
df = pd.concat([df.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)
df.head()

,order,session ID,price,page,date,price 2_bool,country_1,country_2,country_3,country_4,...,colour_13,colour_14,location_1,location_2,location_3,location_4,location_5,location_6,model photography_1,model photography_2
0,1,1,28.0,1,2008-04-01,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
1,2,1,33.0,1,2008-04-01,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
2,3,1,52.0,1,2008-04-01,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
3,4,1,38.0,1,2008-04-01,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
4,5,1,52.0,1,2008-04-01,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True

## 2. Standardize the magnitude of the numeric features

In [47]:
# Initialize and fit-transform with StandardScaler
scaler = StandardScaler()
scaled_array = scaler.fit_transform(df[['price']])

# Extract the “price” column as a DataFrame, not a Series
price_df = df[['price']]

# Fit and transform 'price'
scaled_price = scaler.fit_transform(price_df)

# Put the scaled values back into DataFrame
df['price_scaled'] = scaled_price

## 3. Split into testing and training datasets

In [50]:
# split data into test and training sets
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)